var CSS = {
        DISCUSSION_EDIT: 'forumplusone-thread-edit',
        DISCUSSION_EXPANDED: 'forumplusone-thread-article-expanded',
        POST_EDIT: 'forumplusone-post-edit'
    },
    SELECTORS = {
        ADD_DISCUSSION: '#newdiscussionform',
        ADD_DISCUSSION_TARGET: '.forumplusone-add-discussion-target',
        ALL_FORMS: '.forumplusone-reply-wrapper form',
        CANONIC_REPLY_FORM: '.forumplusone-footer-reply',
        CONTAINER: '.mod-forumplusone-posts-container',
        CONTAINER_LINKS: '.mod-forumplusone-posts-container a',
        DISCUSSION: '.forumplusone-thread',
        DISCUSSIONS: '.forumplusone-threads-wrapper',
        DISCUSSION_EDIT: '.' + CSS.DISCUSSION_EDIT,
        DISCUSSION_BY_ID: '.forumplusone-thread[data-discussionid="%d"]',
        DISCUSSION_COUNT: '.forumplusone-discussion-count',
        DISCUSSION_STATE_BTN_TOGGLE_BY_DISCUSSION_ID: 'article[data-discussionid="%d"] .forumplusone-toggle-state-link',
        DISCUSSION_WRAPPER_BY_DISCUSSION_ID: 'article[data-discussionid="%d"]',
        DISCUSSION_TARGET: '.forumplusone-new-discussion-target',
        DISCUSSION_TEMPLATE: '#forumplusone-discussion-template',
        DISCUSSION_VIEW: '.forumplusone-thread-view',
        EDITABLE_MESSAGE: '[contenteditable]',
        FORM: '.forumplusone-form',
        FORM_ADVANCED: '.forumplusone-use-advanced',
        FORM_REPLY_WRAPPER: '.forumplusone-reply-wrapper',
        INPUT_FORUM: 'input[name="forum"]',
        INPUT_MESSAGE: 'textarea[name="message"]',
        INPUT_REPLY: 'input[name="reply"]',
        INPUT_SUBJECT: 'input[name="subject"]',
        LINK_CANCEL: '.forumplusone-cancel',
        NO_DISCUSSIONS: '.forumnodiscuss',
        NOTIFICATION: '.forumplusone-notification',
        OPTIONS_TO_PROCESS: '.forumplusone-options-menu.unprocessed',
        PLACEHOLDER: '.thread-replies-placeholder',
        POSTS: '.forumplusone-thread-replies',
        POST_BY_ID: '.forumplusone-post-target[data-postid="%d"]',
        POST_EDIT: '.' + CSS.POST_EDIT,
        POST_TARGET: '.forumplusone-post-target',
        RATE: '.forum-post-rating',
        RATE_POPUP: '.forum-post-rating a',
        REPLY_TEMPLATE: '#forumplusone-reply-template',
        SEARCH_PAGE: '#page-mod-forumplusone-search',
        VALIDATION_ERRORS: '.forumplusone-validation-errors',
        VIEW_POSTS: '.forumplusone-view-posts',
        VOTERS_LINK_BY_POST_ID: '.forumplusone-post-target[data-postid="%d"] .forumplusone-show-voters-link',
        VOTE_BTN_BY_POST_ID: '.forumplusone-post-target[data-postid="%d"] .forumplusone-vote-link',
        VOTES_COUNTER_BY_POST_ID: '.forumplusone-post-target[data-postid="%d"] .forumplusone-votes-counter'
    },
    EVENTS = {
        DISCUSSION_CREATED: 'discussion:created',
        DISCUSSION_DELETED: 'discussion:deleted',
        FORM_CANCELED: 'form:canceled',
        POST_CREATED: 'post:created',
        POST_DELETED: 'post:deleted',
        POST_UPDATED: 'post:updated'
    };

M.mod_forumplusone = M.mod_forumplusone || {};
