var CSS = {
        DISCUSSION_EDIT: 'forumimproved-thread-edit',
        DISCUSSION_EXPANDED: 'forumimproved-thread-article-expanded',
        POST_EDIT: 'forumimproved-post-edit'
    },
    SELECTORS = {
        ADD_DISCUSSION: '#newdiscussionform',
        ADD_DISCUSSION_TARGET: '.forumimproved-add-discussion-target',
        ALL_FORMS: '.forumimproved-reply-wrapper form',
        CONTAINER: '.mod-forumimproved-posts-container',
        CONTAINER_LINKS: '.mod-forumimproved-posts-container a',
        DISCUSSION: '.forumimproved-thread',
        DISCUSSIONS: '.forumimproved-threads-wrapper',
        DISCUSSION_EDIT: '.' + CSS.DISCUSSION_EDIT,
        DISCUSSION_BY_ID: '.forumimproved-thread[data-discussionid="%d"]',
        DISCUSSION_COUNT: '.forumimproved-discussion-count',
        DISCUSSION_STATE_BTN_TOGGLE_BY_DISCUSSION_ID: 'article[data-discussionid="%d"] .forumimproved-toggle-state-link',
        DISCUSSION_WRAPPER_BY_DISCUSSION_ID: 'article[data-discussionid="%d"]',
        DISCUSSION_TARGET: '.forumimproved-new-discussion-target',
        DISCUSSION_TEMPLATE: '#forumimproved-discussion-template',
        DISCUSSION_VIEW: '.forumimproved-thread-view',
        EDITABLE_MESSAGE: '[contenteditable]',
        FORM: '.forumimproved-form',
        FORM_ADVANCED: '.forumimproved-use-advanced',
        FORM_REPLY_WRAPPER: '.forumimproved-reply-wrapper',
        INPUT_FORUM: 'input[name="forum"]',
        INPUT_MESSAGE: 'textarea[name="message"]',
        INPUT_REPLY: 'input[name="reply"]',
        INPUT_SUBJECT: 'input[name="subject"]',
        LINK_CANCEL: '.forumimproved-cancel',
        NO_DISCUSSIONS: '.forumnodiscuss',
        NOTIFICATION: '.forumimproved-notification',
        OPTIONS_TO_PROCESS: '.forumimproved-options-menu.unprocessed',
        PLACEHOLDER: '.thread-replies-placeholder',
        POSTS: '.forumimproved-thread-replies',
        POST_BY_ID: '.forumimproved-post-target[data-postid="%d"]',
        POST_EDIT: '.' + CSS.POST_EDIT,
        POST_TARGET: '.forumimproved-post-target',
        RATE: '.forum-post-rating',
        RATE_POPUP: '.forum-post-rating a',
        REPLY_TEMPLATE: '#forumimproved-reply-template',
        SEARCH_PAGE: '#page-mod-forumimproved-search',
        VALIDATION_ERRORS: '.forumimproved-validation-errors',
        VIEW_POSTS: '.forumimproved-view-posts',
        VOTERS_LINK_BY_POST_ID: '.forumimproved-post-target[data-postid="%d"] .forumimproved-show-voters-link',
        VOTE_BTN_BY_POST_ID: '.forumimproved-post-target[data-postid="%d"] .forumimproved-vote-link',
        VOTES_COUNTER_BY_POST_ID: '.forumimproved-post-target[data-postid="%d"] .forumimproved-votes-counter'
    },
    EVENTS = {
        DISCUSSION_CREATED: 'discussion:created',
        DISCUSSION_DELETED: 'discussion:deleted',
        FORM_CANCELED: 'form:canceled',
        POST_CREATED: 'post:created',
        POST_DELETED: 'post:deleted',
        POST_UPDATED: 'post:updated'
    };

M.mod_forumimproved = M.mod_forumimproved || {};
